repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    pass_filenames: true
    additional_dependencies: [pydantic]
    exclude: ^src/holosoma_inference/
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.3
  hooks:
  - id: clang-format
    files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|m|mm|proto|textproto|vert|cu)$
    exclude: ^generated/.*$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
    # exclude .dae, .obj, .mtl, .stl files
    exclude: \.(dae|obj|mtl|stl)$
  - id: trailing-whitespace
    exclude: \.(dae|obj|mtl|stl)$
  - id: mixed-line-ending
    args: [--fix=lf] # Ensures consistent line endings (LF) and removes CR
    exclude: \.(dae|obj|mtl|stl)$
